/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KllFEz2LYLt
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function Login_form() {
  return (
      <Card className="box-border w-full md:w-2/5 ml-10 md:ml-0 mr-10 mt-10 bg-[var(--form)] border border-black rounded-b-md rounded-none rounded-t-md">
        <CardHeader className="space-y-1 pt-10">
          <CardTitle className="text-2xl font-cutive_mono">INGRESA</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-4 font-urbanist">
            <div className="space-y-2">
              <Label htmlFor="email">USUARIO O CORREO</Label>
              <Input id="email" placeholder="m@example.com" required type="email" className="bg-white border border-black rounded-md shadow-xl"/>
            </div>
            <div className="space-y-2">
              <div className="flex items-center">
                <Label htmlFor="password">CONTRASEÑA</Label>
                
              </div>
              <Input id="password" required type="password" className="bg-white border border-black rounded-md shadow-xl"/>
              <Link className="ml-auto inline-block text-sm underline" href="#">
                  ¿Olvidaste tu contraseña?
                </Link>
            </div>
            <Button className="w-full" type="submit">
              ENTRAR
            </Button>
          </div>
        </CardContent>
      </Card>
    
  )
}
