/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1ErEb7uKm7q
 */
import { Progress } from "@/components/ui/progress"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { Input } from "@/components/ui/input"
interface TareaProps {
  color: string;
  description: string;
}

export function Tarea({ tarea }: { tarea: TareaProps }) {
  const { color, description } = tarea;
  return (
    <Dialog>
      <DialogTrigger>
        <div
            // className="w-full max-w-md p-4 border rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors duration-200 shadow-2xl shadow-gray-500/50"
            className="w-full max-w-md p-4 border rounded-lg hover:bg-gray-100 hover:shadow-xl shadow-gray-500/50 dark:hover:bg-gray-800 transition-colors duration-100"
            style={{
              borderBottom: "2px solid black",
              transform: "perspective(1000px) rotateX(20deg)",
            }}
          >
            <div className="flex justify-between items-start">
              <div className="space-y-1">
                <h3 className="font-medium text-lg">Task Title</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  {description}
                </p>
              </div>
            </div>
            <div className="mt-4">
              <Progress value={44} />
            </div>
          </div>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>...</DialogTitle>
          <DialogDescription>
          <div className="space-y-2">
              <h4 className="font-medium leading-none">Edit Task</h4>
              <div className="grid gap-2">
                <div className="space-y-1">
                  <Label htmlFor="person-assigned">Person Assigned</Label>
                  <Select defaultValue="Select person">
                    <SelectTrigger className="w-full">
                      <SelectValue placeholder="Select person" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Person 1">Person 1</SelectItem>
                      <SelectItem value="Person 2">Person 2</SelectItem>
                      <SelectItem value="Person 3">Person 3</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-1">
                  <Label htmlFor="task-description">Task Description</Label>
                  <Textarea
                    className="h-32"
                    defaultValue="This is a placeholder task description. It's meant to give you an idea of how this component will look with your actual task description."
                    id="task-description"
                  />
                </div>
                <div className="space-y-1">
                  <Label className="flex justify-between items-center w-full" htmlFor="task-status">
                    Task Status
                    <Progress className="w-1/2" value={44} />
                  </Label>
                  <Select defaultValue="Select status">
                    <SelectTrigger className="w-full">
                      <SelectValue placeholder="Select status" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Assigned">Assigned</SelectItem>
                      <SelectItem value="Doing">Doing</SelectItem>
                      <SelectItem value="Done">Done</SelectItem>
                      <SelectItem value="Reviewed">Reviewed</SelectItem>
                      <SelectItem value="Archived">Archived</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-1">
                  <Label htmlFor="delivery-date">Delivery Date</Label>
                  <Input className="w-full" id="delivery-date" type="date" />
                </div>
                <Button className="w-full">Save Changes</Button>
              </div>
            </div>
          </DialogDescription>
        </DialogHeader>
      </DialogContent>
    </Dialog>

    
  )
}
