'use client'
import React, { useState } from 'react';
import {
    Card,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
  } from "@/components/ui/card"
  import {
    Carousel,
    CarouselContent,
    CarouselItem,
    CarouselNext,
    CarouselPrevious,
  } from "@/components/ui/carousel"
  
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Xzhcp9mLTpW
 */

type Props = {
  fotos: {
    url: string;
    description: string;
  }[],
  elegida: string;
};

export function Foto_existente({ fotos, elegida }: Props) {
    return (
        <Carousel className="w-full h-full m-[-10]">
            <CarouselContent>
                {fotos.map((foto, index) => (
                    <CarouselItem key={index}>
                        <div className="p-1">
                        <Card >
                            <CardContent className="flex aspect-square items-center justify-center p-6">
                            <img
                                src={foto.url}
                                alt="Photo by Drew Beamer"
                                // fill
                                className="rounded-md object-cover"
                            />
                            {/* <span className="text-4xl font-semibold">{foto.url}</span> */}
                            </CardContent>
                        </Card>
                        </div>
                    </CarouselItem>
                ))}
            </CarouselContent>
            <CarouselPrevious />
            <CarouselNext />
        </Carousel>
    )
}