'use client'
import React, { useState } from 'react';

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Xzhcp9mLTpW
 */
import { Button } from "@/components/ui/button"
  
import { Progress } from "@/components/ui/progress"
import { Label } from "@/components/ui/label"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { Input } from "@/components/ui/input"

type Props = {
  tarea: {
    asignado: string;
    mensaje: number;
    descripcion: string;
    fechaLimite: string;
    progreso: number;
  };
};

export function Tarea_existente({ tarea }: Props) {
      const personas = [
        { value: 'mikejones', label: 'mikejones' },
        { value: 'Person 2', label: 'Person 2' },
        { value: 'Person 3', label: 'Person 3' }
      ];
      const status = [
        { value: 0, label: 'Asignada' },
        { value: 25, label: 'Haciendo' },
        { value: 50, label: 'Hecha' },
        { value: 75, label: 'Revisada' },
        { value: 100, label: 'Archivada' }
      ];
    return (
        <div className="space-y-2">
            <div className="grid gap-2">
                <div className="space-y-1">
                <Label htmlFor="person-assigned">Persona Asignada</Label>
                <Select defaultValue={tarea.asignado}>
                    <SelectTrigger className="w-full">
                    <SelectValue placeholder="Select person" />
                    </SelectTrigger>
                    <SelectContent>
                    {personas.map((item, index) => (
                        <SelectItem key={`${index}-persona`} value={item.value}>{item.label}</SelectItem>
                    ))}
                    </SelectContent>
                </Select>
                </div>
                <div className="space-y-1">
                <Label htmlFor="task-description">Descripción</Label>
                <Textarea
                    className="h-32"
                    defaultValue={tarea.descripcion}
                    id="task-description"
                />
                </div>
                <div className="space-y-1">
                <Label className="flex justify-between items-center w-full" htmlFor="task-status">
                    Progreso
                    <Progress className="w-1/2" value={44} />
                </Label>
                <Select defaultValue={tarea.progreso.toString()}>
                    <SelectTrigger className="w-full">
                    <SelectValue placeholder="Select status" />
                    </SelectTrigger>
                    <SelectContent>
                    {status.map(item => (
                        <SelectItem key={item.value} value={item.value.toString()}>{item.label}</SelectItem>
                    ))}
                    </SelectContent>
                </Select>
                </div>
                <div className="space-y-1">
                <Label htmlFor="delivery-date">Fecha Límite</Label>
                <Input className="w-full" id="delivery-date" type="date" />
                </div>
                <Button className="w-full">Guardar Cambios</Button>
            </div>
        </div>
    )
}
