'use client'
import React, { useState } from 'react';
import Image from "next/image"

import { AspectRatio } from "@/components/ui/aspect-ratio"

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Xzhcp9mLTpW
 */
import { Button } from "@/components/ui/button"
import {
    Card,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
  } from "@/components/ui/card"
  import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
  } from "@/components/ui/dialog"
  import {
    Carousel,
    CarouselContent,
    CarouselItem,
    CarouselNext,
    CarouselPrevious,
  } from "@/components/ui/carousel"
  
import { ScrollArea } from "@/components/ui/scroll-area"
export function Fotos_sidebar() {
  // Tasks
  const [clickedTask, setClickedTask] = useState<number | null>(null);
  const handleClick = (index: number) => {
    setClickedTask(index === clickedTask ? null : index);
  };
  const tasks = [
    { color: 'green-500', description: 'This is a description of the task.' },
    { color: 'yellow-500', description: 'This is a description of the task.' },    
  ];
  const images = [
    { url: '/next.svg', description: 'This is a description of the task.' },
    { url: '/vercel.svg', description: 'This is a description of the task.' },    
  ];
  return (
    <section>
        <CardContent className='px-0'>
            <div key="1" className="flex flex-col h-full w-64">
                <ScrollArea className="flex-1 py-2">
                <div className="px-4 space-y-4">
                    {images.map((image, index) => (
                        <Dialog key={`${index}-foto`}>
                        <AspectRatio ratio={16/9} className="bg-muted">
                        <DialogTrigger> 
                        <Image
                                src={image.url}
                                alt="Photo by Drew Beamer"
                                fill
                                className="rounded-md object-cover"
                            />
                        </DialogTrigger>
                        </AspectRatio>
                        <DialogContent className='min-w-[400px]'>
                            <DialogHeader>
                            <DialogTitle>Imagen {index}</DialogTitle>
                            <DialogDescription>
                                <Carousel>
                                <CarouselContent>
                                    {images.map((imagecarrusel, index) => (
                                        <CarouselItem key={`${index}-imagecarrusel`}>
                                            <Image
                                                src={imagecarrusel.url}
                                                alt="Photo by Drew Beamer"
                                                fill
                                                className="rounded-md object-cover"
                                            />
                                        </CarouselItem>
                                    ))}
                                    
                                    <CarouselItem>...</CarouselItem>
                                    <CarouselItem>...</CarouselItem>
                                </CarouselContent>
                                <CarouselPrevious />
                                <CarouselNext />
                                </Carousel>
                            </DialogDescription>
                            </DialogHeader>
                        </DialogContent>
                        </Dialog>
                    ))}

                
                </div>
                </ScrollArea>
                
            </div>
        </CardContent>
        <CardFooter className='sticky bottom-0 z-10 bg-background'>
            <Button className="w-full" size="sm">
                Add Task
            </Button>
        </CardFooter>
    </section>
    
  )
}