'use client'
import React, { useState } from 'react';

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Xzhcp9mLTpW
 */
import { Button } from "@/components/ui/button"
import {
    Card,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
  } from "@/components/ui/card"
import { ScrollArea } from "@/components/ui/scroll-area"
export function Productos_sidebar() {
  // Tasks
  const [clickedTask, setClickedTask] = useState<number | null>(null);
  const handleClick = (index: number) => {
    setClickedTask(index === clickedTask ? null : index);
  };
  const tasks = [
    { color: 'green-500', description: 'This is a description of the task.' },
    { color: 'yellow-500', description: 'This is a description of the task.' },
    { color: 'red-500', description: 'This is a description of the task.' },
    { color: 'green-500', description: 'This is a description of the task.' },
    { color: 'yellow-500', description: 'This is a description of the task.' },
    { color: 'red-500', description: 'This is a description of the task.' },
    { color: 'green-500', description: 'This is a description of the task.' },
    { color: 'green-500', description: 'This is a description of the task.' },
    { color: 'yellow-500', description: 'This is a description of the task.' },
    { color: 'red-500', description: 'This is a description of the task.' },
    { color: 'green-500', description: 'This is a description of the task.' },
    { color: 'yellow-500', description: 'This is a description of the task.' },
    { color: 'red-500', description: 'This is a description of the task.' },
    { color: 'green-500', description: 'This is a description of the task.' },
    { color: 'green-500', description: 'This is a description of the task.' },
    { color: 'yellow-500', description: 'This is a description of the task.' },
    { color: 'red-500', description: 'This is a description of the task.' },
    { color: 'green-500', description: 'This is a description of the task.' },
    { color: 'yellow-500', description: 'This is a description of the task.' },
    { color: 'red-500', description: 'This is a description of the task.' },
    { color: 'green-500', description: 'This is a description of the task.' },
    { color: 'green-500', description: 'This is a description of the task.' },
    { color: 'yellow-500', description: 'This is a description of the task.' },
    { color: 'red-500', description: 'This is a description of the task.' },
    { color: 'green-500', description: 'This is a description of the task.' },
    { color: 'yellow-500', description: 'This is a description of the task.' },
    { color: 'red-500', description: 'This is a description of the task.' },
    { color: 'green-500', description: 'This is a description of the task.' },
  ];
  return (
    <section>
        <CardContent>
            <div key="1" className="flex flex-col h-full w-64">
                <ScrollArea className="flex-1 py-2">
                <div className="px-4 space-y-4">
                {tasks.map((task, index) => (
                    <div
                    key={index}
                    className={`flex items-start gap-2 p-2 ${
                        clickedTask === index ? 'bg-gray-300' : 'hover:bg-gray-200'
                    }`}
                    onClick={() => handleClick(index)}
                    >
                    <span className={`flex h-2 w-2 rounded-full bg-${task.color}`} />
                    <input
                        type="text" 
                        className="text-sm text-gray-500 dark:text-gray-400 outline-none border-none"
                        value={task.description}
                        readOnly
                    />
                    </div>
                ))}
                </div>
                </ScrollArea>
                
            </div>
        </CardContent>
        <CardFooter className='sticky bottom-0 z-10 bg-background'>
            <Button className="w-full" size="sm">
                Add Task
            </Button>
        </CardFooter>
    </section>
    
  )
}